# Generated by Django 4.2.2 on 2023-10-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Nouveau'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vedette',
            field=models.BooleanField(default=False, verbose_name='Vedette'),
        ),
    ]
