# Generated by Django 4.2.2 on 2023-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_is_new_product_is_vedette'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_secondary',
            field=models.ImageField(default=1, upload_to='product_images/', verbose_name='image secondaire'),
            preserve_default=False,
        ),
    ]
