# Generated by Django 4.2.2 on 2023-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_image_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
    ]
