# Generated by Django 4.2.2 on 2023-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_product_additional_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.TextField(null=True, verbose_name='Info Garantie'),
        ),
    ]
