# Generated by Django 4.2.2 on 2023-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_specification_product_warranty_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camera_quality',
            field=models.CharField(max_length=150, null=True, verbose_name='Camera'),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=150, null=True, verbose_name='Ecran'),
        ),
        migrations.AddField(
            model_name='product',
            name='graphics',
            field=models.CharField(max_length=150, null=True, verbose_name='Graphisme'),
        ),
        migrations.AddField(
            model_name='product',
            name='harddisk_capacity',
            field=models.CharField(max_length=150, null=True, verbose_name='Disque Dur'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(max_length=150, null=True, verbose_name='Memoire RAM'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_capacity',
            field=models.CharField(max_length=150, null=True, verbose_name='Processeur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
    ]
