# Generated by Django 4.2.2 on 2023-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_product_camera_quality_alter_product_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='ecommerce.keyword'),
        ),
    ]
