# Generated by Django 4.2.2 on 2023-10-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_remove_keyword_product_product_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_set', to='ecommerce.product', verbose_name='produit'),
            preserve_default=False,
        ),
    ]
