# Generated by Django 4.2.2 on 2023-10-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_product_keywords_keyword_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
    ]
