# Generated by Django 4.2.2 on 2023-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text="Utilisez des balises personnalisées pour formater le texte.<br> <h5 style='font-weight: bold; margin-bottom: 0;'># Les sous titres #</h5> <br> ___ pour Séparation horizontale <br> <strong>*gras*</strong> <br> <em>-italique-</em> <br> _ <u>souligner</u> _"),
        ),
    ]
