# Generated by Django 4.2.2 on 2023-10-25 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_confirmed',
            field=models.BooleanField(default=False, verbose_name='Numéro de téléphone confirmé'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='numéro de téléphone'),
        ),
    ]
