# Generated by Django 4.2.2 on 2023-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_phone_number_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='numéro de téléphone'),
        ),
    ]
