# Generated by Django 4.2.2 on 2023-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_manage', '0003_promocode_alter_cartitem_price_cart_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='cart_manage.cartitem'),
        ),
    ]
