# Generated by Django 4.2.2 on 2023-10-14 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_manage', '0005_remove_cart_items_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='promo_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(help_text='Réduction en pourcentage (ex: 10 pour 10%)'),
        ),
    ]
