# Generated by Django 4.2.2 on 2023-11-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_manage', '0008_rename_date_ordered_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_manage.promocode'),
        ),
    ]
